name: Auto Update JSON

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering with specific label

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Adjust as needed

    - name: Run PHP Script
      run: |
        php generate_matches.php > output.json
        if [ $? -ne 0 ]; then
          echo "PHP script failed to execute correctly. Check the script for errors."
          exit 1
        fi

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add output.json
        git commit -m "Auto Update JSON #1: Manually run by ak47demon"
        git push
